# Generated by Django 5.0.1 on 2026-01-11 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_agencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_users', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='agency_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agencyuser',
            unique_together={('agency', 'user')},
        ),
    ]
