# Generated by Django 5.0.1 on 2026-01-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta Ads'), ('google', 'Google Ads'), ('ga4', 'Google Analytics 4')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(choices=[('campaign', 'Campaign'), ('ad_set', 'Ad Set'), ('ad', 'Ad'), ('account', 'Account')], max_length=20)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('account_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('conversions', models.BigIntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_metrics', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Daily Metric',
                'verbose_name_plural': 'Daily Metrics',
                'db_table': 'daily_metrics',
                'ordering': ['-date', 'entity_type'],
                'indexes': [models.Index(fields=['agency', 'date'], name='daily_metri_agency__aa28cc_idx'), models.Index(fields=['account_id', 'date'], name='daily_metri_account_659e54_idx'), models.Index(fields=['platform', 'date'], name='daily_metri_platfor_55a211_idx'), models.Index(fields=['entity_id', 'date'], name='daily_metri_entity__7ad608_idx')],
                'unique_together': {('platform', 'entity_type', 'entity_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta Ads'), ('google', 'Google Ads'), ('ga4', 'Google Analytics 4')], max_length=20)),
                ('account_id', models.CharField(db_index=True, max_length=100)),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_conversions', models.BigIntegerField(default=0)),
                ('total_conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_ctr', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_roas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Metric Snapshot',
                'verbose_name_plural': 'Metric Snapshots',
                'db_table': 'metric_snapshots',
                'indexes': [models.Index(fields=['agency', 'period_start'], name='metric_snap_agency__f69091_idx'), models.Index(fields=['account_id', 'period_start'], name='metric_snap_account_a7261b_idx')],
                'unique_together': {('platform', 'account_id', 'granularity', 'period_start')},
            },
        ),
    ]
