# Generated by Django 5.0.1 on 2026-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
