# Generated by Django 5.0.1 on 2026-01-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('property_id', models.CharField(blank=True, max_length=100)),
                ('property_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_integrations', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'GA4 Integration',
                'verbose_name_plural': 'GA4 Integrations',
                'db_table': 'ga4_integrations',
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('developer_token', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_integrations', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Google Ads Integration',
                'verbose_name_plural': 'Google Ads Integrations',
                'db_table': 'google_ads_integrations',
            },
        ),
        migrations.CreateModel(
            name='MetaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_integrations', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Meta Integration',
                'verbose_name_plural': 'Meta Integrations',
                'db_table': 'meta_integrations',
            },
        ),
    ]
