# Generated by Django 5.0.1 on 2026-01-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaintegration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
