# Generated by Django 5.0.1 on 2026-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_metaintegration_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadsintegration',
            name='account_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
