# Generated by Django 5.0.1 on 2026-02-10 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('account_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_ads_accounts',
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('campaign_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('campaign_type', models.CharField(blank=True, max_length=100)),
                ('daily_budget', models.CharField(blank=True, max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='google_ads.googleadsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_ads_campaigns',
                'unique_together': {('user', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsAdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('ad_group_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='google_ads.googleadsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_ad_groups', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='google_ads.googleadscampaign')),
            ],
            options={
                'db_table': 'google_ads_ad_groups',
                'unique_together': {('user', 'ad_group_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('customer_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('descriptive_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_ads_customers',
                'unique_together': {('user', 'customer_id')},
            },
        ),
        migrations.AddField(
            model_name='googleadsaccount',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='google_ads.googleadscustomer'),
        ),
        migrations.CreateModel(
            name='GoogleAdsAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('ad_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('ad_type', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='google_ads.googleadsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_ads', to=settings.AUTH_USER_MODEL)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='google_ads.googleadsadgroup')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='google_ads.googleadscampaign')),
            ],
            options={
                'db_table': 'google_ads_ads',
                'unique_together': {('user', 'ad_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='googleadsaccount',
            unique_together={('user', 'account_id')},
        ),
        migrations.CreateModel(
            name='GoogleAdsInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('account', 'Account'), ('campaign', 'Campaign'), ('ad_group', 'Ad Group'), ('ad', 'Ad')], max_length=20)),
                ('object_id', models.CharField(max_length=64)),
                ('google_user_id', models.CharField(max_length=64)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_ads_insights',
                'unique_together': {('date', 'level', 'object_id')},
            },
        ),
    ]
