# Generated by Django 5.0.1 on 2026-01-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta Ads'), ('google', 'Google Ads')], max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('account_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted'), ('archived', 'Archived')], max_length=20)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_created_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted'), ('archived', 'Archived')], max_length=20)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('targeting', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_created_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sets', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Ad Set',
                'verbose_name_plural': 'Ad Sets',
                'db_table': 'ad_sets',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted'), ('archived', 'Archived')], max_length=20)),
                ('creative', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_created_at', models.DateTimeField(blank=True, null=True)),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='campaigns.adset')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'db_table': 'ads',
                'unique_together': {('ad_set', 'external_id')},
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['agency', 'platform'], name='campaigns_agency__64eeee_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['account_id'], name='campaigns_account_f17499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('platform', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='adset',
            unique_together={('campaign', 'external_id')},
        ),
    ]
