# Generated by Django 5.0.1 on 2026-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('account_id', models.CharField(max_length=64)),
                ('status', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('timezone_offset_hours_utc', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'meta_accounts',
            },
        ),
        migrations.CreateModel(
            name='MetaAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('ad_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('creative', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'meta_ads',
            },
        ),
        migrations.CreateModel(
            name='MetaAdset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('adset_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('optimization_goal', models.CharField(blank=True, max_length=100)),
                ('daily_budget', models.CharField(blank=True, max_length=32)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meta_adsets',
            },
        ),
        migrations.CreateModel(
            name='MetaBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('business_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meta_businesses',
            },
        ),
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('campaign_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('daily_budget', models.CharField(blank=True, max_length=32)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meta_campaigns',
            },
        ),
        migrations.CreateModel(
            name='MetaInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('account', 'Account'), ('campaign', 'Campaign'), ('adset', 'Adset'), ('ad', 'Ad')], max_length=20)),
                ('object_id', models.CharField(max_length=64)),
                ('meta_user_id', models.CharField(max_length=64)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('action_values', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'meta_insights',
            },
        ),
    ]
