# Generated by Django 5.0.1 on 2026-02-10 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metaaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaad',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta.metaaccount'),
        ),
        migrations.AddField(
            model_name='metaad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaadset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta.metaaccount'),
        ),
        migrations.AddField(
            model_name='metaadset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_adsets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaad',
            name='adset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta.metaadset'),
        ),
        migrations.AddField(
            model_name='metabusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaadset',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.metabusiness'),
        ),
        migrations.AddField(
            model_name='metaad',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.metabusiness'),
        ),
        migrations.AddField(
            model_name='metaaccount',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='meta.metabusiness'),
        ),
        migrations.AddField(
            model_name='metacampaign',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='meta.metaaccount'),
        ),
        migrations.AddField(
            model_name='metacampaign',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.metabusiness'),
        ),
        migrations.AddField(
            model_name='metacampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaadset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta.metacampaign'),
        ),
        migrations.AddField(
            model_name='metaad',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta.metacampaign'),
        ),
        migrations.AddField(
            model_name='metainsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='metabusiness',
            unique_together={('user', 'business_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metaaccount',
            unique_together={('user', 'account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metacampaign',
            unique_together={('user', 'campaign_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metaadset',
            unique_together={('user', 'adset_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metaad',
            unique_together={('user', 'ad_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metainsight',
            unique_together={('date', 'level', 'object_id')},
        ),
    ]
