# Generated by Django 5.0.1 on 2026-02-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('page_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('page_access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meta_pages',
                'unique_together': {('user', 'page_id')},
            },
        ),
        migrations.CreateModel(
            name='MetaLeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('form_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_lead_forms', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_forms', to='meta.metapage')),
            ],
            options={
                'db_table': 'meta_lead_forms',
                'unique_together': {('user', 'form_id')},
            },
        ),
        migrations.CreateModel(
            name='MetaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_user_id', models.CharField(max_length=64)),
                ('lead_id', models.CharField(max_length=64)),
                ('created_time', models.DateTimeField()),
                ('field_data', models.JSONField(default=list)),
                ('ad_id', models.CharField(blank=True, max_length=64)),
                ('ad_name', models.CharField(blank=True, max_length=255)),
                ('adset_id', models.CharField(blank=True, max_length=64)),
                ('adset_name', models.CharField(blank=True, max_length=255)),
                ('campaign_id', models.CharField(blank=True, max_length=64)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('form_id_str', models.CharField(blank=True, max_length=64)),
                ('is_organic', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_leads', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='meta.metaleadform')),
            ],
            options={
                'db_table': 'meta_leads',
                'unique_together': {('user', 'lead_id')},
            },
        ),
    ]
