# Generated by Django 5.0.1 on 2026-02-10 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Token',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ga4_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('google_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ga4_tokens',
            },
        ),
        migrations.CreateModel(
            name='GA4User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ga4_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('google_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ga4_users',
            },
        ),
        migrations.CreateModel(
            name='GoogleToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='google_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('google_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'google_tokens',
            },
        ),
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='google_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('google_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_users',
            },
        ),
        migrations.CreateModel(
            name='MetaToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('meta_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('token', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'meta_tokens',
            },
        ),
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('meta_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meta_users',
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('state', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('meta', 'Meta'), ('google', 'Google'), ('ga4', 'GA4')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_states',
            },
        ),
    ]
