# Generated by Django 5.0.1 on 2026-01-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'meta_ads_business',
            },
        ),
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta User',
                'verbose_name_plural': 'Meta Users',
                'db_table': 'meta_ads_metauser',
            },
        ),
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('account_status', models.IntegerField(default=1)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_accounts', to='meta_ads.business')),
            ],
            options={
                'verbose_name': 'Ad Account',
                'verbose_name_plural': 'Ad Accounts',
                'db_table': 'meta_ads_adaccount',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('buying_type', models.CharField(blank=True, max_length=50)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='meta_ads.adaccount')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'meta_ads_campaign',
            },
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('optimization_goal', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta_ads.adaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta_ads.campaign')),
            ],
            options={
                'verbose_name': 'Ad Set',
                'verbose_name_plural': 'Ad Sets',
                'db_table': 'meta_ads_adset',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('effective_status', models.CharField(blank=True, max_length=50)),
                ('creative_id', models.CharField(blank=True, max_length=50)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.adaccount')),
                ('adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.adset')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.campaign')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'db_table': 'meta_ads_ad',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('account', 'Account'), ('campaign', 'Campaign'), ('adset', 'Ad Set'), ('ad', 'Ad')], max_length=20)),
                ('object_id', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meta_ads.adaccount')),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'db_table': 'meta_ads_insight',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='meta_ads.metauser'),
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(default='meta', max_length=20)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('business', 'Business'), ('ad_account', 'Ad Account'), ('campaign', 'Campaign'), ('adset', 'Ad Set'), ('ad', 'Ad'), ('creative', 'Creative'), ('insights', 'Insights')], max_length=20)),
                ('entity_id', models.CharField(max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_insight_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Sync State',
                'verbose_name_plural': 'Sync States',
                'db_table': 'meta_ads_syncstate',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('object_story_spec', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='meta_ads.adaccount')),
            ],
            options={
                'verbose_name': 'Ad Creative',
                'verbose_name_plural': 'Ad Creatives',
                'db_table': 'meta_ads_adcreative',
                'indexes': [models.Index(fields=['ad_account'], name='meta_ads_ad_ad_acco_fa0e25_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgencyAdAccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_accesses', to='meta_ads.adaccount')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_account_accesses', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agency Ad Account Access',
                'verbose_name_plural': 'Agency Ad Account Accesses',
                'db_table': 'meta_ads_agencyadaccountaccess',
                'indexes': [models.Index(fields=['agency'], name='meta_ads_ag_agency__af8c5d_idx'), models.Index(fields=['ad_account'], name='meta_ads_ag_ad_acco_f36e5c_idx')],
                'unique_together': {('agency', 'ad_account')},
            },
        ),
        migrations.AddIndex(
            model_name='adaccount',
            index=models.Index(fields=['account_status'], name='meta_ads_ad_account_d48105_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['ad_account', 'status'], name='meta_ads_ca_ad_acco_e95321_idx'),
        ),
        migrations.AddIndex(
            model_name='adset',
            index=models.Index(fields=['campaign', 'status'], name='meta_ads_ad_campaig_ae8cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='adset',
            index=models.Index(fields=['ad_account'], name='meta_ads_ad_ad_acco_d9c250_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['adset', 'status'], name='meta_ads_ad_adset_i_b94167_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['campaign'], name='meta_ads_ad_campaig_93eac3_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['ad_account'], name='meta_ads_ad_ad_acco_65e7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['level', 'object_id'], name='meta_ads_in_level_065c98_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['date_start', 'date_stop'], name='meta_ads_in_date_st_6ddf0d_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['ad_account'], name='meta_ads_in_ad_acco_1bd670_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['level', 'object_id', 'date_start'], name='meta_ads_in_level_21af94_idx'),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(fields=['agency'], name='meta_ads_sy_agency__6c2aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(fields=['entity_type'], name='meta_ads_sy_entity__adb4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(fields=['status'], name='meta_ads_sy_status_cdf676_idx'),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(fields=['agency', 'entity_type'], name='meta_ads_sy_agency__1d1abc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncstate',
            unique_together={('agency', 'provider', 'entity_type', 'entity_id')},
        ),
    ]
