# Generated by Django 5.0.1 on 2026-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpermissions',
            name='meta_form_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
