# Generated by Django 5.0.1 on 2026-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('pathname', models.CharField(blank=True, max_length=500)),
                ('lineno', models.IntegerField(blank=True, null=True)),
                ('funcname', models.CharField(blank=True, max_length=255)),
                ('exc_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'system_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='system_log_created_0feb86_idx'), models.Index(fields=['logger_name', '-created_at'], name='system_log_logger__fb68a7_idx')],
            },
        ),
    ]
