# Generated by Django 5.0.1 on 2026-02-10 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('account_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ga4_accounts',
                'unique_together': {('user', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='GA4Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('property_id', models.CharField(max_length=64)),
                ('google_user_id', models.CharField(max_length=64)),
                ('sessions', models.BigIntegerField(default=0)),
                ('users', models.BigIntegerField(default=0)),
                ('pageviews', models.BigIntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversions', models.BigIntegerField(default=0)),
                ('events', models.BigIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('medium', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ga4_insights',
                'unique_together': {('date', 'property_id', 'source', 'medium')},
            },
        ),
        migrations.CreateModel(
            name='GA4Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=64)),
                ('property_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ga4.ga4account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ga4_properties',
                'unique_together': {('user', 'property_id')},
            },
        ),
    ]
